WIP Cumulus-478 Adding docs for granule-storage
cumulus-nasa/cumulus-nasa.github.io pull request #53
Opened 2018-05-29 14:31 UTC by kkelly51

2018-05-29 15:38 UTC, sethvincent approved these changes

2018-05-29 15:43 UTC, sethvincent commented
The failing build seems unrelated to this PR and I can help get that fixed.

2018-05-29 17:14 UTC, laurenfrederick requested changes

2018-05-29 17:14 UTC, laurenfrederick commented on docs/worklow-configuration-how-to.md
> +The second file, `MOD09GQ.A2017025.h21v00.006.2017034065104.hdf.met`, does not have it's own `url_path` so it will use the collection `url_path` and have a final file path of `s3://cumulus-test-sandb
This would be in the private bucket. I think for these examples, you should use the buckets above i.e. `sample-private-bucket`

2018-05-29 17:14 UTC, laurenfrederick commented on docs/worklow-configuration-how-to.md
> +buckets:
I think we should say something like bucket types should be internal, public, private, or protected. Maybe a description of what that means - internal is for system use, public would be publicly available, protected behind ED login, and private for... private info.

2018-05-29 17:14 UTC, laurenfrederick commented on docs/worklow-configuration-how-to.md
> +Instead of hardcoding the placement, the `url_path` can be a template to be populated with metadata during the move-granules step. For example:
We need an explanation here that the Move Granules step needs to be added to the workflow in order for this to work.

2018-05-29 17:14 UTC, laurenfrederick commented on docs/worklow-configuration-how-to.md
> +"url_path": "{cmrMetadata.Granule.Collection.ShortName}"
I think it seems kind of obvious, but we should specify that by putting cmrMetdata, the CMR granule XML generated by the processing step is being used, that it's going into the XML nodes to pull that data out. So you'd need to have a step in your workflow that generates the cmr xml.

2018-05-29 17:14 UTC, laurenfrederick commented on docs/worklow-configuration-how-to.md
> +"url_path": "{cmrMetadata.Granule.Collection.ShortName}/{substring(file.name, 0, 3)}"
Should explain substring.

2018-05-29 17:14 UTC, laurenfrederick commented on docs/worklow-configuration-how-to.md
> +"cmrMetadata": {
I would take cmrMetadata out and grab the example in XML format since that is what is generated

2018-05-29 17:14 UTC, laurenfrederick commented on docs/worklow-configuration-how-to.md
> +The following examples of `url_path` could be used.
Then add an example of url_path using some of these, say something like if you wanted to organize granules into folders by month and year you would configure it this way.

2018-05-29 18:09 UTC, bilts submitted a review, later dismissed
I agree with the changes Lauren proposed.

Additionally, I'd add one overall summary example that organizes granules in a way we expect would be common among the DAACs (`s3://<protected-bucket>/<collection-id>/<year>/<day-of-year>/<granule-id>.<ext>`)

2018-05-29 19:16 UTC, laurenfrederick commented on docs/workflow-configuration-how-to.md
> +`public` indicates a complete public bucket.
completely

2018-05-30 14:36 UTC, laurenfrederick approved these changes

2018-06-06 19:12 UTC, merged